import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { sendTwilioMessage } from '../_shared/twilioMessaging.ts';
import { deliveryMessage, type RiderContact } from '../_shared/orderTracking.ts';
import { hashPhone, loadCostContext, recordOutboundMessage } from '../_shared/whatsappCostLedger.ts';
// Dispatch capability is generated by the DB trigger, never supplied by a customer.
Deno.serve(async req => {
  if (req.method !== 'POST') return new Response(null, { status: 405 });
  const db = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  try {
    const { event_id, dispatch_token } = await req.json();
    if (!event_id || !dispatch_token) return new Response(null, { status: 403 });
    const { data: ev } = await db.from('whatsapp_delivery_events').update({ state: 'sending' })
      .eq('id', event_id).eq('dispatch_token', dispatch_token).eq('state', 'pending').select('*').maybeSingle();
    if (!ev) return new Response(null, { status: 204 });
    const finish = async (state: string, failure_reason: string | null = null, sid: string | null = null) => {
      await db.from('whatsapp_delivery_events').update({ state, failure_reason, provider_sid: sid, sent_at: state === 'sent' ? new Date().toISOString() : null }).eq('id', ev.id);
      return Response.json({ state });
    };
    const { data: order } = await db.from('orders').select('id,user_id,channel,delivery_type,status,rider_id,tracking_token,order_number').eq('id', ev.order_id).maybeSingle();
    if (!order || order.channel !== 'whatsapp' || order.delivery_type !== 'delivery' || order.status !== ev.status || order.rider_id !== ev.rider_id) return await finish('superseded');
    const { data: session } = await db.from('whatsapp_sessions').select('phone,last_message_at').eq('customer_user_id', order.user_id).order('last_message_at', { ascending: false }).limit(1).maybeSingle();
    if (!session?.phone) return await finish('blocked', 'no_customer_session');
    // No approved lifecycle template is configured. Never substitute an unrelated template.
    if (!session.last_message_at || Date.now() - Date.parse(session.last_message_at) >= 24 * 60 * 60 * 1000) return await finish('blocked', 'approved_lifecycle_template_required');
    const { data: snapshot } = await db.rpc('get_secure_order_tracking', { p_token: order.tracking_token });

    // Assigned rider contact: read only from the rider's own profile, and only
    // for the rider currently assigned to this order (a reassignment or a
    // cancellation supersedes the event above, so no stale number can be sent).
    let riderContact: RiderContact | null = null;
    const isAssignment = String(ev.event_key || '').startsWith('assigned:') || ev.status === 'assigned';
    if (isAssignment && ev.rider_id && order.rider_id === ev.rider_id) {
      const [{ data: riderProfile }, { data: riderRecord }] = await Promise.all([
        db.from('profiles').select('full_name, phone, phone_verified').eq('user_id', ev.rider_id).maybeSingle(),
        db.from('rider_profiles').select('vehicle_type').eq('user_id', ev.rider_id).maybeSingle(),
      ]);
      riderContact = {
        name: riderProfile?.full_name ?? null,
        phone: riderProfile?.phone ?? null,
        phoneVerified: riderProfile?.phone_verified ?? false,
        vehicleType: riderRecord?.vehicle_type ?? null,
      };
    }

    const body = deliveryMessage(ev, order, snapshot, riderContact);
    if (!body) return await finish('blocked', 'unsupported_event');
    const result = await sendTwilioMessage(db, { channel: 'whatsapp', to: session.phone, body, poll: true });

    // Actual provider cost of this status notification, recorded once per
    // event/SID. `absorbed` — the customer already paid the upfront allowance
    // at checkout and is never re-billed; this feeds margin reporting only.
    try {
      const { data: envRow } = await db.from('platform_settings').select('value').eq('key', 'platform_environment').maybeSingle();
      const costCtx = await loadCostContext(db, 'twilio/whatsapp-message', envRow?.value || 'development');
      await recordOutboundMessage(db, costCtx, {
        providerEventId: result.sid ? `wa-out:sid:${result.sid}` : `wa-status:${ev.id}`,
        messageSid: result.sid ?? null,
        category: 'service',
        windowState: 'in_window',
        failed: !result.ok,
        statusMessage: true,
        notes: `order_status:${ev.status}`,
        phoneHash: await hashPhone(session.phone),
        customerUserId: order.user_id,
        orderId: order.id,
      });
    } catch (e) {
      console.error('[wa-status] cost record failed (non-blocking)', e instanceof Error ? e.message : e);
    }

    return await finish(result.ok ? 'sent' : result.error_code === 63016 ? 'blocked' : 'failed', result.ok ? null : String(result.error_code || result.error || 'send_failed'), result.sid || null);
  } catch {
    // Unknown transport outcomes are NOT automatically retried: doing so could duplicate a delivered message.
    return Response.json({ error: 'dispatch_failed' }, { status: 500 });
  }
});
