import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { sendTwilioMessage } from '../_shared/twilioMessaging.ts';
import { deliveryMessage } from '../_shared/orderTracking.ts';
// Dispatch capability is generated by the DB trigger, never supplied by a customer.
Deno.serve(async req => {
  if (req.method !== 'POST') return new Response(null, { status: 405 });
  const db = createClient(Deno.env.get('SUPABASE_URL')!, Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
  try {
    const { event_id, dispatch_token } = await req.json();
    if (!event_id || !dispatch_token) return new Response(null, { status: 403 });
    const { data: ev } = await db.from('whatsapp_delivery_events').update({ state: 'sending' })
      .eq('id', event_id).eq('dispatch_token', dispatch_token).eq('state', 'pending').select('*').maybeSingle();
    if (!ev) return new Response(null, { status: 204 });
    const finish = async (state: string, failure_reason: string | null = null, sid: string | null = null) => {
      await db.from('whatsapp_delivery_events').update({ state, failure_reason, provider_sid: sid, sent_at: state === 'sent' ? new Date().toISOString() : null }).eq('id', ev.id);
      return Response.json({ state });
    };
    const { data: order } = await db.from('orders').select('id,user_id,channel,delivery_type,status,rider_id,tracking_token,order_number').eq('id', ev.order_id).maybeSingle();
    if (!order || order.channel !== 'whatsapp' || order.delivery_type !== 'delivery' || order.status !== ev.status || order.rider_id !== ev.rider_id) return await finish('superseded');
    const { data: session } = await db.from('whatsapp_sessions').select('phone,last_message_at').eq('customer_user_id', order.user_id).order('last_message_at', { ascending: false }).limit(1).maybeSingle();
    if (!session?.phone) return await finish('blocked', 'no_customer_session');
    // No approved lifecycle template is configured. Never substitute an unrelated template.
    if (!session.last_message_at || Date.now() - Date.parse(session.last_message_at) >= 24 * 60 * 60 * 1000) return await finish('blocked', 'approved_lifecycle_template_required');
    const { data: snapshot } = await db.rpc('get_secure_order_tracking', { p_token: order.tracking_token });
    const body = deliveryMessage(ev, order, snapshot);
    if (!body) return await finish('blocked', 'unsupported_event');
    const result = await sendTwilioMessage(db, { channel: 'whatsapp', to: session.phone, body, poll: true });
    return await finish(result.ok ? 'sent' : result.error_code === 63016 ? 'blocked' : 'failed', result.ok ? null : String(result.error_code || result.error || 'send_failed'), result.sid || null);
  } catch {
    // Unknown transport outcomes are NOT automatically retried: doing so could duplicate a delivered message.
    return Response.json({ error: 'dispatch_failed' }, { status: 500 });
  }
});
