import { useState, useEffect, useMemo } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/hooks/useAuth';
import { useCart } from '@/hooks/useCart';
import { useTakeawayPacks } from '@/hooks/useTakeawayPacks';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { BottomNav } from '@/components/home/BottomNav';
import { CartItemCard } from '@/components/cart/CartItemCard';
import { OrderSummary } from '@/components/cart/OrderSummary';
import { AddressSelector } from '@/components/cart/AddressSelector';
import { TakeawayPackDisplay } from '@/components/cart/TakeawayPackDisplay';
import { ArrowLeft, ShoppingBag, Leaf, Loader2 } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import type { Tables } from '@/integrations/supabase/types';

type Address = Tables<'addresses'>;

export default function Cart() {
  const { user, loading: authLoading } = useAuth();
  const { items, vendorId, vendorName, subtotal, totalCalories, clearCart } = useCart();
  const { getApplicablePacks } = useTakeawayPacks(vendorId);
  const navigate = useNavigate();
  const { toast } = useToast();

  const [addresses, setAddresses] = useState<Address[]>([]);
  const [selectedAddress, setSelectedAddress] = useState<Address | null>(null);
  const [loadingAddresses, setLoadingAddresses] = useState(true);
  const [placingOrder, setPlacingOrder] = useState(false);

  // Calculate applicable takeaway packs
  const applicablePacks = useMemo(() => {
    return getApplicablePacks(items.map(item => ({ productId: item.productId, quantity: item.quantity })));
  }, [items, getApplicablePacks]);

  const packagingFee = useMemo(() => {
    return applicablePacks.reduce((sum, pack) => sum + pack.price, 0);
  }, [applicablePacks]);

  const deliveryFee = 500;
  const serviceFee = 100;
  const total = subtotal + deliveryFee + serviceFee + packagingFee;

  useEffect(() => {
    if (!authLoading && !user) {
      navigate('/auth');
    }
  }, [user, authLoading, navigate]);

  useEffect(() => {
    if (user) {
      fetchAddresses();
    }
  }, [user]);

  const fetchAddresses = async () => {
    if (!user) return;
    
    try {
      const { data, error } = await supabase
        .from('addresses')
        .select('*')
        .eq('user_id', user.id)
        .order('is_default', { ascending: false });

      if (error) throw error;
      
      setAddresses(data || []);
      
      // Auto-select default or first address
      const defaultAddr = data?.find(a => a.is_default) || data?.[0];
      if (defaultAddr) {
        setSelectedAddress(defaultAddr);
      }
    } catch (error) {
      console.error('Error fetching addresses:', error);
    } finally {
      setLoadingAddresses(false);
    }
  };

  const handlePlaceOrder = async () => {
    if (!user || !vendorId || items.length === 0) return;

    if (!selectedAddress) {
      toast({
        title: 'No delivery address',
        description: 'Please select or add a delivery address',
        variant: 'destructive',
      });
      return;
    }

    setPlacingOrder(true);
    try {
      // Create order
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          user_id: user.id,
          vendor_id: vendorId,
          order_number: '', // Will be generated by trigger
          subtotal,
          delivery_fee: deliveryFee,
          service_fee: serviceFee,
          total,
          total_calories: totalCalories,
          delivery_address_id: selectedAddress.id,
          delivery_address_text: `${selectedAddress.address_line}, ${selectedAddress.city}, ${selectedAddress.state}`,
          status: 'pending',
          payment_status: 'pending',
        })
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = items.map(item => ({
        order_id: order.id,
        product_id: item.productId,
        product_name: item.productName,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity,
        calories: item.calories * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      // Log calories
      await supabase
        .from('calorie_logs')
        .insert({
          user_id: user.id,
          order_id: order.id,
          calories: totalCalories,
          meal_type: 'order',
        });

      // Clear cart
      clearCart();

      toast({
        title: 'Order placed!',
        description: `Your order ${order.order_number} has been placed successfully`,
      });

      // Navigate to order confirmation or orders page
      navigate('/orders');
    } catch (error) {
      console.error('Error placing order:', error);
      toast({
        title: 'Error',
        description: 'Failed to place order. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setPlacingOrder(false);
    }
  };

  if (authLoading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="flex flex-col items-center gap-4">
          <div className="w-16 h-16 rounded-2xl bg-primary flex items-center justify-center animate-pulse-soft">
            <Leaf className="w-9 h-9 text-primary-foreground" />
          </div>
          <p className="text-muted-foreground">Loading...</p>
        </div>
      </div>
    );
  }

  if (!user) return null;

  return (
    <div className="min-h-screen bg-background pb-32">
      {/* Header */}
      <header className="sticky top-0 z-20 bg-background/95 backdrop-blur-md border-b border-border">
        <div className="container flex items-center gap-4 py-4">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate(-1)}
            className="shrink-0"
          >
            <ArrowLeft className="w-5 h-5" />
          </Button>
          <div className="flex-1">
            <h1 className="text-xl font-bold text-foreground">Your Cart</h1>
            {vendorName && (
              <p className="text-sm text-muted-foreground">From {vendorName}</p>
            )}
          </div>
        </div>
      </header>

      <main className="container py-6 space-y-6">
        {items.length === 0 ? (
          <div className="text-center py-16">
            <div className="w-20 h-20 mx-auto mb-6 rounded-2xl bg-secondary flex items-center justify-center">
              <ShoppingBag className="w-10 h-10 text-muted-foreground" />
            </div>
            <h2 className="text-xl font-bold text-foreground mb-2">Your cart is empty</h2>
            <p className="text-muted-foreground mb-6">
              Add items from a restaurant to get started
            </p>
            <Button onClick={() => navigate('/')}>
              Browse Restaurants
            </Button>
          </div>
        ) : (
          <>
            {/* Cart Items */}
            <section className="space-y-3">
              <h2 className="font-semibold text-foreground">Order Items</h2>
              {items.map((item) => (
                <CartItemCard key={item.id} item={item} />
              ))}
            </section>

            {/* Takeaway Packs */}
            {applicablePacks.length > 0 && (
              <TakeawayPackDisplay packs={applicablePacks} />
            )}

            {/* Address Selector */}
            <AddressSelector
              addresses={addresses}
              selectedAddress={selectedAddress}
              onSelect={setSelectedAddress}
              loading={loadingAddresses}
              userId={user.id}
              onAddressAdded={fetchAddresses}
            />

            {/* Order Summary */}
            <OrderSummary
              subtotal={subtotal}
              deliveryFee={deliveryFee}
              serviceFee={serviceFee}
              total={total}
              totalCalories={totalCalories}
              packagingFee={packagingFee}
            />
          </>
        )}
      </main>

      {/* Checkout Button */}
      {items.length > 0 && (
        <div className="fixed bottom-16 left-0 right-0 bg-background border-t border-border p-4 safe-bottom z-40">
          <div className="container">
            <Button 
              className="w-full h-14 text-base font-semibold shadow-button"
              onClick={handlePlaceOrder}
              disabled={placingOrder || !selectedAddress}
            >
              {placingOrder ? (
                <>
                  <Loader2 className="w-5 h-5 mr-2 animate-spin" />
                  Placing Order...
                </>
              ) : (
                <>
                  Place Order • ₦{total.toLocaleString()}
                </>
              )}
            </Button>
          </div>
        </div>
      )}

      <BottomNav />
    </div>
  );
}
